<a href="https://colab.research.google.com/github/djajsla999/2020-2-AI/blob/master/Code/01_tf_begin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#코랩 시작

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [ ]:
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
a=[2,3,4]
a

[2, 3, 4]

In [ ]:
s = "hello, tensorflow"
s

'hello, tensorflow'

In [ ]:
s

'hello, tensorflow'

In [ ]:
import tensorflow as tf
tf. __version__

a = tf.constant(5)
b = tf.constant(3)
print(a+b)

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
c = tf.constant("Hello, world!")
print(c)
print(c.numpy())

tf.Tensor(b'Hello, world!', shape=(), dtype=string)
b'Hello, world!'


In [ ]:
# 텐서플로 1.0 버전 선택

try:
  %tensorflow_version 1.x
except Exception:
  pass

import tensorflow as tf
tf. __version__

'1.15.2'

In [ ]:
import tensorflow as tf

hello = tf.constant("Hello World!")

sess = tf.Session()
print(sess.run(hello))
sess.close()

b'Hello World!'


In [ ]:
a = 10
b = 10
print(tf.add(a, b))

sess = tf.Session()
print(sess.run(hello))
sess.close()

Tensor("Add_2:0", shape=(), dtype=int32)
b'Hello World!'


In [ ]:
%tensorflow_version s.x

Unknown TensorFlow version: s.x
Currently selected TF version: 2.x
Available versions:
 * 1.x
 * 2.x


In [ ]:
import tensorflow as tf
tf. __version__

a = tf.constant(5)
b = tf.constant(3)
print(a+b)

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
c = tf.constant('Hello, world!')
print(c)
print(c.numpy())

tf.Tensor(b'Hello, world!', shape=(), dtype=string)
b'Hello, world!'


In [ ]:
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
a.shape

TensorShape([])

In [ ]:
a.numpy()

3

In [ ]:
b = tf.constant(3.)
b

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
a = tf.constant([1, 2, 3])
a.shape

TensorShape([3])

In [ ]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
a.shape

TensorShape([2, 3])

In [ ]:
a = tf.constant([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
a.shape

TensorShape([2, 2, 3])

In [ ]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

print(res)
print(res.numpy())

tf.Tensor(2.0, shape=(), dtype=float32)
2.0


In [ ]:
x = tf.constant(2)
y = tf.constant(5)
def f1(): return tf.multiply(x, 17)
def f2(): return tf.add(y, 23)
r = tf.cond(tf.less(x, y), f1, f2)

#less    x<y
#2*17 = 34
r.numpy()


34

In [ ]:
t = tf.constant([1, 2, 3])
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([5, 6, 7])

print((x+y).numpy())

[ 6  8 10]


In [ ]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
print(a.numpy())

d = a * b + c

print(d)
# 값만 출력
print(d.numpy())

[5.]
tf.Tensor([52.], shape=(1,), dtype=float32)
[52.]


In [ ]:
x = tf.constant(([0], [10], [20], [30]))
y = tf.constant([0, 1, 2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np

#[012]
print(np.arange(3))
#3*3행렬에 모두 1.0을 집어넣는다.
print(np.ones((3, 3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
#중간고사나옴
#[123]
x = tf.constant((np.arange(3)))
#[5]
y = tf.constant([5], dtype=tf.int64)
print((x+y).numpy())
#[567]

x = tf.constant((np.ones((3, 3))))
y = tf.constant(np.arange(3), dtype=tf.double)
print((x+y).numpy())

#reshpe 3*1로 모양 바꾸기
x = tf.constant(np.arange(3).reshape(3, 1))
y = tf.constant(np.arange(3))
print((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
